name: Deploy static content to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install dependencies (opcional, si necesitas build)
        run: |
          npm install
          npm run build
          
      - name: Move files to root (CRUCIAL)
        run: |
          mkdir -p dist
          cp -r src/* dist/ || true
          cp src/index.html dist/ || true
          
      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: "none"
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist'  # Cambiado a la carpeta con tus archivos
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
